### ISSUE TITLE
Document pre-deliverable proposal and incubation work mode in charter

### ISSUE THREAD

**Issue by hober** [privacycg/privacycg.github.io#2]
The intended lifecycle of a proposal in our CG is described [in our proposals repository](https://github.com/privacycg/proposals). Broadly, our work is done in two phases:

1. The **proposal** phase, AKA **incubation**. This is an extremely lightweight, WICG-style process. Anyone in the group can make proposals at any time. Incubation produces & iterates on **explainers**. Successful incubation results in a **deliverable**. (Moving to the deliverable phase requires multi-implementer interest; this is because the CG is committed to a multi-stakeholder, multi-engine web.)
2. The **deliverable** phase, AKA **specification**. This is an efficient, WHATWG-like process, during which we iterate on explainers and **specifications** simultaneously. Successful specification results in migration of the work to a standards-track Working Group or to the equivalent in other standards bodies.

Our [charter](https://privacycg.github.io/charter.html) predominantly describes how we work on deliverables, and when we migrate things elsewhere, but does not say much about how we work on proposals that have not yet become deliverables. That phase is currently only laid out in our proposals repository.

This can leave readers of our charter (e.g. AC reps considering a join request) unaware of our enthusiasm for new proposals and the WICG-like process we have in place for working on them. Worse, readers may think we aren't a venue interested in or equipped for early-stage incubation.

We may want to document the earlier phase in our charter (hence this issue). Alternately, we could raise visibility of this aspect of things in some other way, via an FAQ on the website or some such.

**Comment by cwilso** [comment]
That seems at precise odds with W3C Process, which would presume the deliverable phase is under the guise of a Working Group (which can actually work on Recommendation-track deliverables).  I would have presumed a Community Group was ONLY working on early-stage incubation.

**Comment by travisleithead** [comment]
@hober, glad to see your clarifications; honestly, was surprised by some of it--I hadn't understood the charter to read quite that way. The charter certainly has room for improvement, hopefully not at the expense of making it longer and more complicated... 🙁.

This is a bit long; I'll hit on a few points summarized here and described in more detail below.

* Microsoft plans to participate in a dedicated Community Group established to bring together privacy-minded folks in a forum that can foster discussion and consensus-building around proposals.
* We’d like more clarity on how the incubation process is applied in the charter, especially on the sub-steps of incubation this CG will do.
* The charter language suggests the CG is "creating standards", which if taken literally is overstepping the nature of a CG. That needs fixing/clarification. See [issues 3](https://github.com/privacycg/privacycg.github.io/issues/3).
* We need to clarify expectations about which group(s) will consume the deliverables of this CG. It’s confusing to call out WebAppSec WG since its expertise is security not privacy. Should we be spinning up a Privacy WG as the next step in the pipeline? How would that WG relate to the Privacy IG, which has taken on wide review of other specs for privacy considerations?

First, Microsoft is happy to have a dedicated community group to bring together privacy-minded folks in a forum that can foster discussion and consensus-building around proposals (incubations). I think we all recognize privacy as a major customer concern and want to work together with the community to create future standards that have broad consensus and can be implemented by all browsers.

My summary of the OP is that it attempts to bring more clarity and discrete steps to the general concept of "incubation". Incubation has been loosely defined (by design) in the WICG. A broad definition is good because it allows a CG to cast the widest possible net to attract the most diverse proposals. But it's a double-edged sword leading to confusion around what is "early" incubation vs. "mature" incubation (or steps in between). Explainers quickly become spec-like using Bikeshed templates and then it's very hard to tell what the maturity status of the document is. See the recent emphasis erring on the side of "less official" by [painting a "DRAFT" watermark in the CG Report's template](https://github.com/w3c/tr-design/pull/177). On my first read, the clarifications in the OP were not visible in the current charter. I have reservations about some of the terminology; I'm also concerned about the process rigor implied by taking up a "deliverable", which sounds like a CG to WG transition, not a CG incubation milestone. In general, I like the concept of bringing a bit more clarity around the "sub-steps" of incubation.

Another concern is about various places where the CG asserts its authority to create standards. This appears to be overstepping the scope of a CG. Take for example the heading ["Standardization"](https://github.com/privacycg/proposals#standardization) which IMO would be better termed "Pre-Standardization", or the leading sentence in the charter ["to develop privacy-focused web standards"](https://privacycg.github.io/charter.html#mission) which is not something this CG can actually do in isolation. (The Scope section says it better as ["will discuss proposals for"](https://privacycg.github.io/charter.html#scope). This CG does not create standards and its deliverables are not standards; the charter should be much clearer on this point.

Taking a step back, the privacy effort at W3C has some oddities compared with other mature "horizontal" activities (e.g., i18n, a11y). Privacy was exclusively the realm of PING, until this CG was setup. PING was probably doing too much for its scope as an interest group anyway. With a Privacy CG we can now start to incubate proposals for standards and will ["take into consideration outputs of PING when evaluating proposals."](https://privacycg.github.io/charter.html#w3c-coordination) For this CG's output, there is no privacy-focused upstream working group available with the charter to standardize privacy-related specifications. The current charter uses WebAppSec (a security-focused group) as a proxy for a privacy working group, but that does not seem appropriate. Rather, I would expect a separate Privacy WG that many folks currently working in PING (for example) might join. It would be good to start planning for an actual Privacy WG in which to graduate privacy standards from this CG.

**Comment by hober** [comment]
Thanks everyone, and especially @travisleithead for translating. I'm going to try to get a PR up today to address most or all of this.

**Comment by cwilso** [comment]
I'd like to explicitly strongly second that we should get the ball rolling on a Privacy WG.  And maybe develop that charter openly.

**Comment by hober** [comment]
Fixed in 32bd9e8.
